name: medt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0
  - attrs=20.1.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - cryptography=3.1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36h9f0ad1d_1001
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=1.7.0=py36h9f0ad1d_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1
  - ipykernel=5.3.4=py36h95af2a2_0
  - ipython=7.16.1=py36h95af2a2_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.2=py36h9f0ad1d_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - json5=0.9.4=pyh9f0ad1d_0
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - jupyterlab=2.2.6=py_0
  - jupyterlab_server=1.2.0=py_0
  - ld_impl_linux-64
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran-ng
  - libsodium=1.0.18
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1=py36h9f0ad1d_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2
  - notebook=6.1.3=py36h9f0ad1d_0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1g
  - packaging=20.4=pyh9f0ad1d_0
  - pandoc=2.10.1
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pip=20.1.1=py36_1
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.7=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.16.0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.10
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pyzmq=19.0.2
  - readline=8.0
  - requests=2.24.0=pyh9f0ad1d_0
  - send2trash=1.5.0=py_0
  - setuptools=47.3.1=py36_0
  - six=1.15.0=py_0
  - sqlite=3.32.3
  - terminado=0.8.3
  - testpath=0.4.4=py_0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3=py36h9f0ad1d_1
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py36_0
  - widgetsnbextension=3.5.1=py36h9f0ad1d_1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0=py_0
  - zlib=1.2.11
  - pip:
    - ci-info==0.2.0
    - click==7.1.2
    - cython==0.29.20
    - et-xmlfile==1.0.1
    - etelemetry==0.2.1
    - filelock==3.0.12
    - isodate==0.6.0
    - jdcal==1.4.1
    - joblib==0.17.0
    - lxml==4.5.1
    - matplotlib==3.3.2
    - medpy==0.4.0
    - natsort==7.0.1
    - nibabel==3.1.0
    - nipype==1.5.0
    - openpyxl==3.0.4
    - prov==1.5.3
    - pydicom==2.0.0
    - pydot==1.4.1
    - pydotplus==2.0.2
    - pynrrd==0.4.2
    - rdflib==5.0.0
    - scikit-learn==0.23.2
    - scipy==1.5.3
    - setproctitle==1.1.10
    - simplejson==3.17.0
    - threadpoolctl==2.1.0
    - torch==1.4.0
    - torch-dwconv==0.1.0
    - torchvision==0.4.0
    - traits==6.1.0
prefix: ~/anaconda3/envs/medt

